apiVersion: v1
kind: Pod
metadata:
  name: infinite-container
spec:
  restartPolicy: Always
  containers:
  - name: container1
    image: alpine:3.12.0
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
      - name: shared-volume
        mountPath: /etc/a
  - name: container2
    image: alpine:3.12.0
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
      - name: shared-volume
        mountPath: /etc/b
  volumes:
  - name: shared-volume
    emptyDir: {}


#kubectl apply -f pod.yaml